apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitcoin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitcoin
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "bitcoin.labels" . | nindent 8 }}
    spec:
      containers:
        - name: bitcoind
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -{{ .Values.network }}
            - -rpcuser={{ .Values.rpc.user }}
            - -rpcpassword={{ .Values.rpc.password }}
            - -rpcallowip=0.0.0.0/0
            - -rpcbind=0.0.0.0
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /home/bitcoin/.bitcoin
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "bitcoin.fullname" . }}
      {{- end }}
