apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shophub.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shophub.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwtSecret: {{ .Values.backend.jwtSecret | quote }}
