apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "shop-operator.fullname" . }}
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["shop.shophub.io"]
    resources: ["shops", "shops/status", "shops/finalizers", "discordchannels", "discordchannels/status", "discordchannels/finalizers", "wallets", "wallets/status", "wallets/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps", "secrets", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["clusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["redis.redis.opstreelabs.in"]
    resources: ["redis"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources: ["servicemonitors", "podmonitors", "prometheusrules", "alertmanagerconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "shop-operator.fullname" . }}
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "shop-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "shop-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
