apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "celestia.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "celestia.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: celestia
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "celestia.labels" . | nindent 8 }}
    spec:
      containers:
        - name: celestia
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celestia
            - {{ .Values.nodeType }}
            - start
            - --p2p.network={{ .Values.network }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /home/celestia
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "celestia.fullname" . }}
      {{- end }}
