{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop.name" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets | nindent 2 }}
{{- end }}
