apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop.name" . }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/instance: {{ include "shop.name" . }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop.name" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "shop.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/instance: {{ include "shop.name" . }}
    app.kubernetes.io/component: frontend
